name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - run: node --version
      - run: npm --version
      - run: npm i -g newman
      - run: npm i -g newman-reporter-htmlextra --force
      - run: newman run https://api.postman.com/collections/38058293-bbaac405-94e3-4864-89ec-b0bddc96a27e?access_key=PMAT-01J70R5YH2YBFQ4YDCZHXH8ZQE -r htmlextra
       
      # - run: newman run IslamicAppAuthPractice.postman_collection.json
