name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - run: node --version
      - run: npm --version
      - run: npm i -g newman
      - run: npm i -g newman-reporter-htmlextra
      - run: newman run sample_postman_collection.json
    
    